/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_io_u4;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Britany Morales
 */
public class EOP extends javax.swing.JFrame {

    /**
     * Creates new form EOP
     */
    public EOP() {
        initComponents();
        this.setExtendedState(EOQ.MAXIMIZED_BOTH);
        txtQP.setEditable(false);
        txtIM.setEditable(false);
        txtIP.setEditable(false);
        txtPA.setEditable(false);
        txtCCA.setEditable(false);
        txtCOA.setEditable(false);
        txtCT.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCOA = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        txtCCA = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        txtQP = new javax.swing.JTextField();
        txtIM = new javax.swing.JTextField();
        txtPA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        txtCT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        txtCMA = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDA = new javax.swing.JTextField();
        txtCU = new javax.swing.JTextField();
        txtCM = new javax.swing.JTextField();
        txtDAN = new javax.swing.JTextField();
        btnCal = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        txtCO = new javax.swing.JTextField();
        txtPD = new javax.swing.JTextField();
        txtDD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 228, 178));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(126, 170, 146));

        jButton1.setBackground(new java.awt.Color(158, 210, 190));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Regresar.png"))); // NOI18N
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" CANTIDAD ECONÓMICA A PRODUCIR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274)
                .addComponent(jLabel1)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 90));

        jPanel4.setBackground(new java.awt.Color(209, 231, 191));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Resultados:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 60, 60));
        jLabel3.setText("<html>Cantidad <p> óptima a producir:<html>");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("Costo de mantenimiento anual:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 60, 60));
        jLabel5.setText("Producciones anuales:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 60, 60));
        jLabel6.setText("Inventario promedio:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 110, 10));

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, 10));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, 10));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(60, 60, 60));
        jLabel13.setText("Costo de compra anual:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(60, 60, 60));
        jLabel16.setText("Costo de orden anual:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        txtCOA.setBackground(new java.awt.Color(209, 231, 191));
        txtCOA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCOA.setForeground(new java.awt.Color(51, 51, 51));
        txtCOA.setBorder(null);
        txtCOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOAActionPerformed(evt);
            }
        });
        jPanel4.add(txtCOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 110, 21));

        txtIP.setBackground(new java.awt.Color(209, 231, 191));
        txtIP.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtIP.setForeground(new java.awt.Color(51, 51, 51));
        txtIP.setBorder(null);
        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });
        jPanel4.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 120, 21));

        txtCCA.setBackground(new java.awt.Color(209, 231, 191));
        txtCCA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCCA.setForeground(new java.awt.Color(51, 51, 51));
        txtCCA.setBorder(null);
        txtCCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCAActionPerformed(evt);
            }
        });
        jPanel4.add(txtCCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 120, 21));

        jSeparator14.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 110, 10));

        jSeparator15.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 110, 10));

        txtQP.setBackground(new java.awt.Color(209, 231, 191));
        txtQP.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtQP.setForeground(new java.awt.Color(51, 51, 51));
        txtQP.setBorder(null);
        txtQP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQPActionPerformed(evt);
            }
        });
        jPanel4.add(txtQP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, 21));

        txtIM.setBackground(new java.awt.Color(209, 231, 191));
        txtIM.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtIM.setForeground(new java.awt.Color(51, 51, 51));
        txtIM.setBorder(null);
        txtIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMActionPerformed(evt);
            }
        });
        jPanel4.add(txtIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 110, 21));

        txtPA.setBackground(new java.awt.Color(209, 231, 191));
        txtPA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPA.setForeground(new java.awt.Color(51, 51, 51));
        txtPA.setBorder(null);
        txtPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAActionPerformed(evt);
            }
        });
        jPanel4.add(txtPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 110, 21));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(60, 60, 60));
        jLabel20.setText("Costo total:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jSeparator18.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 120, 10));

        txtCT.setBackground(new java.awt.Color(209, 231, 191));
        txtCT.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCT.setForeground(new java.awt.Color(51, 51, 51));
        txtCT.setBorder(null);
        txtCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTActionPerformed(evt);
            }
        });
        jPanel4.add(txtCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 120, 21));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(60, 60, 60));
        jLabel8.setText("Inventario máximo:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jSeparator19.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 120, 10));

        txtCMA.setBackground(new java.awt.Color(209, 231, 191));
        txtCMA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCMA.setForeground(new java.awt.Color(51, 51, 51));
        txtCMA.setBorder(null);
        txtCMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMAActionPerformed(evt);
            }
        });
        jPanel4.add(txtCMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, 21));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 780, 500));

        jPanel5.setBackground(new java.awt.Color(209, 231, 191));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Datos a ingresar:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 31));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(60, 60, 60));
        jLabel7.setText("Demanda anual:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(60, 60, 60));
        jLabel11.setText("Costo por mantener:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(60, 60, 60));
        jLabel12.setText("Costo unitario:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtDA.setBackground(new java.awt.Color(209, 231, 191));
        txtDA.setForeground(new java.awt.Color(153, 153, 153));
        txtDA.setText("D");
        txtDA.setBorder(null);
        txtDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDAMousePressed(evt);
            }
        });
        txtDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDAActionPerformed(evt);
            }
        });
        txtDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDAKeyTyped(evt);
            }
        });
        jPanel5.add(txtDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, 21));

        txtCU.setBackground(new java.awt.Color(209, 231, 191));
        txtCU.setForeground(new java.awt.Color(153, 153, 153));
        txtCU.setText("C");
        txtCU.setBorder(null);
        txtCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCUMousePressed(evt);
            }
        });
        txtCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUActionPerformed(evt);
            }
        });
        txtCU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCUKeyTyped(evt);
            }
        });
        jPanel5.add(txtCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 130, 21));

        txtCM.setBackground(new java.awt.Color(209, 231, 191));
        txtCM.setForeground(new java.awt.Color(153, 153, 153));
        txtCM.setText("H");
        txtCM.setBorder(null);
        txtCM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCMMousePressed(evt);
            }
        });
        txtCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMActionPerformed(evt);
            }
        });
        txtCM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCMKeyTyped(evt);
            }
        });
        jPanel5.add(txtCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, 21));

        txtDAN.setBackground(new java.awt.Color(209, 231, 191));
        txtDAN.setForeground(new java.awt.Color(153, 153, 153));
        txtDAN.setText("0");
        txtDAN.setBorder(null);
        txtDAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDANMousePressed(evt);
            }
        });
        txtDAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDANActionPerformed(evt);
            }
        });
        txtDAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDANKeyTyped(evt);
            }
        });
        jPanel5.add(txtDAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 21));

        btnCal.setBackground(new java.awt.Color(204, 204, 255));
        btnCal.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCal.setForeground(new java.awt.Color(102, 102, 102));
        btnCal.setText("Calcular");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        jPanel5.add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 118, 36));

        btnLim.setBackground(new java.awt.Color(204, 204, 255));
        btnLim.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnLim.setForeground(new java.awt.Color(102, 102, 102));
        btnLim.setText("Limpiar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });
        jPanel5.add(btnLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 118, 36));

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, 10));

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 10));

        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 130, 10));

        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 10));

        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(60, 60, 60));
        jLabel15.setText("Costo por ordenar:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(60, 60, 60));
        jLabel17.setText("Días por año:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(60, 60, 60));
        jLabel18.setText("Demanda diaria:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(60, 60, 60));
        jLabel19.setText("Producción diaria:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jSeparator16.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 130, 10));

        jSeparator17.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 130, 10));

        txtCO.setBackground(new java.awt.Color(209, 231, 191));
        txtCO.setForeground(new java.awt.Color(153, 153, 153));
        txtCO.setText("S");
        txtCO.setBorder(null);
        txtCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCOMousePressed(evt);
            }
        });
        txtCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOActionPerformed(evt);
            }
        });
        txtCO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCOKeyTyped(evt);
            }
        });
        jPanel5.add(txtCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 21));

        txtPD.setBackground(new java.awt.Color(209, 231, 191));
        txtPD.setForeground(new java.awt.Color(153, 153, 153));
        txtPD.setText("p");
        txtPD.setBorder(null);
        txtPD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPDMousePressed(evt);
            }
        });
        txtPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPDActionPerformed(evt);
            }
        });
        txtPD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPDKeyTyped(evt);
            }
        });
        jPanel5.add(txtPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 130, 21));

        txtDD.setBackground(new java.awt.Color(209, 231, 191));
        txtDD.setForeground(new java.awt.Color(153, 153, 153));
        txtDD.setText("d");
        txtDD.setBorder(null);
        txtDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDDMousePressed(evt);
            }
        });
        txtDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDDActionPerformed(evt);
            }
        });
        txtDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDDKeyTyped(evt);
            }
        });
        jPanel5.add(txtDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 130, 21));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 380, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        INDEX regresar = new INDEX();
        regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOAActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtCCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCAActionPerformed

    private void txtQPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQPActionPerformed

    private void txtIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void txtCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTActionPerformed

    private void txtDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDAActionPerformed

    private void txtCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCUActionPerformed

    private void txtCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMActionPerformed

    private void txtDANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDANActionPerformed

    private void txtCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOActionPerformed

    private void txtPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPDActionPerformed

    private void txtDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDDActionPerformed

    private void txtDAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDAMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().equals("D")) {
            txtDA.setText("");
            txtDA.setForeground(Color.black);
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtPD.getText().isEmpty()) {
            txtPD.setText("p");
            txtPD.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
        if (txtDD.getText().isEmpty()) {
            txtDD.setText("d");
            txtDD.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDAMousePressed

    private void txtCOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCOMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().equals("S")) {
            txtCO.setText("");
            txtCO.setForeground(Color.black);
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtPD.getText().isEmpty()) {
            txtPD.setText("p");
            txtPD.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
        if (txtDD.getText().isEmpty()) {
            txtDD.setText("d");
            txtDD.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCOMousePressed

    private void txtCMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().equals("H")) {
            txtCM.setText("");
            txtCM.setForeground(Color.black);
        }
        if (txtPD.getText().isEmpty()) {
            txtPD.setText("p");
            txtPD.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
        if (txtDD.getText().isEmpty()) {
            txtDD.setText("d");
            txtDD.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCMMousePressed

    private void txtPDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPDMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtPD.getText().equals("p")) {
            txtPD.setText("");
            txtPD.setForeground(Color.black);
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
        if (txtDD.getText().isEmpty()) {
            txtDD.setText("d");
            txtDD.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtPDMousePressed

    private void txtDANMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDANMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtPD.getText().isEmpty()) {
            txtPD.setText("p");
            txtPD.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().equals("0")) {
            txtDAN.setText("");
            txtDAN.setForeground(Color.black);
        }
        if (txtDD.getText().isEmpty()) {
            txtDD.setText("d");
            txtDD.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_txtDANMousePressed

    private void txtDDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDDMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtPD.getText().isEmpty()) {
            txtPD.setText("p");
            txtPD.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
        if (txtDD.getText().equals("d")) {
            txtDD.setText("");
            txtDD.setForeground(Color.black);
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_txtDDMousePressed

    private void txtCUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCUMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtPD.getText().isEmpty()) {
            txtPD.setText("p");
            txtPD.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
        if (txtDD.getText().isEmpty()) {
            txtDD.setText("d");
            txtDD.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().equals("C")) {
            txtCU.setText("");
            txtCU.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCUMousePressed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        //Declarar variables
        double demAn, costpOrd, costpMan, produDi, diasxA, costUn, deDiaria, cantOp, invMax, invProm, numProAn, costCompAn, costPedAn, costManAn, costTot;

        demAn = Double.parseDouble(txtDA.getText());
        costpOrd = Double.parseDouble(txtCO.getText());
        costpMan = Double.parseDouble(txtCM.getText());
        produDi = Double.parseDouble(txtPD.getText());
        diasxA = Double.parseDouble(txtDAN.getText());
        deDiaria = Double.parseDouble(txtDD.getText());
        costUn = Double.parseDouble(txtCU.getText());

        //Operaciones
        if (deDiaria == 0 && diasxA != 0) {
            deDiaria = demAn / diasxA;
        }

        cantOp = Math.sqrt((2 * demAn * costpOrd) / (costpMan * (1 - (deDiaria / produDi))));
        invMax = (cantOp * (1 - (deDiaria / produDi)));
        invProm = (cantOp * (1 - (deDiaria / produDi))) / 2;
        numProAn = demAn / cantOp;
        costCompAn = demAn * costUn;
        costPedAn = (demAn / cantOp) * costpOrd;
        costManAn = (cantOp / 2) * (costpMan * (1 - (deDiaria / produDi)));
        costTot = costCompAn + costPedAn + costManAn;

        //Mostrar resultados
        txtQP.setText(String.format("%.2f", cantOp));
        txtIM.setText(String.format("%.2f", invMax));
        txtIP.setText(String.format("%.2f", invProm));
        txtPA.setText(String.format("%.2f", numProAn));
        txtCCA.setText(String.format("%.2f", costCompAn));
        txtCOA.setText(String.format("%.2f", costPedAn));
        txtCMA.setText(String.format("%.2f", costManAn));
        txtCT.setText(String.format("%.2f", costTot));
    }//GEN-LAST:event_btnCalActionPerformed

    private void txtCMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMAActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimActionPerformed

    private void txtDAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDAKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtDAKeyTyped

    private void txtCOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtCOKeyTyped

    private void txtCMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtCMKeyTyped

    private void txtPDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPDKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtPDKeyTyped

    private void txtDANKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDANKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtDANKeyTyped

    private void txtDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDDKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtDDKeyTyped

    private void txtCUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCUKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtCUKeyTyped

    private void Limpiar() {
        for (Component component : jPanel5.getComponents()) {
            if (component instanceof JTextField jTextField) {
                jTextField.setText("");
            }
        }
        for (Component component : jPanel4.getComponents()) {
            if (component instanceof JTextField jTextField) {
                jTextField.setText("");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EOP().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtCCA;
    private javax.swing.JTextField txtCM;
    private javax.swing.JTextField txtCMA;
    private javax.swing.JTextField txtCO;
    private javax.swing.JTextField txtCOA;
    private javax.swing.JTextField txtCT;
    private javax.swing.JTextField txtCU;
    private javax.swing.JTextField txtDA;
    private javax.swing.JTextField txtDAN;
    private javax.swing.JTextField txtDD;
    private javax.swing.JTextField txtIM;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPD;
    private javax.swing.JTextField txtQP;
    // End of variables declaration//GEN-END:variables

}
