/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_io_u4;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vanes
 */
public class EOQ extends javax.swing.JFrame {

    /**
     * Creates new form EOQ
     */
    public EOQ() {
        initComponents();
        this.setExtendedState(EOQ.MAXIMIZED_BOTH);
        txtQ.setEditable(false);
        txtIP.setEditable(false);
        txtPA.setEditable(false);
        txtCCA.setEditable(false);
        txtCOA.setEditable(false);
        txtCMA.setEditable(false);
        txtCT.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCMA = new javax.swing.JTextField();
        txtPA = new javax.swing.JTextField();
        txtCOA = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        txtQ = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        txtCCA = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDA = new javax.swing.JTextField();
        txtCU = new javax.swing.JTextField();
        txtCM = new javax.swing.JTextField();
        txtCO = new javax.swing.JTextField();
        btnCal = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 228, 178));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1370, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(126, 170, 146));

        jButton1.setBackground(new java.awt.Color(158, 210, 190));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Regresar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" CANTIDAD ECONÓMICA A ORDENAR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 90));

        jPanel4.setBackground(new java.awt.Color(209, 231, 191));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Resultados:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 60, 60));
        jLabel3.setText("Cantidad óptima:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("Costo de mantenimiento anual:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 60, 60));
        jLabel5.setText("Pedidos anuales:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 60, 60));
        jLabel6.setText("Inventario promedio:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        txtCT.setBackground(new java.awt.Color(209, 231, 191));
        txtCT.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCT.setForeground(new java.awt.Color(51, 51, 51));
        txtCT.setBorder(null);
        txtCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTActionPerformed(evt);
            }
        });
        jPanel4.add(txtCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, 21));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 110, 10));

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, 10));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, 10));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 120, 10));

        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(60, 60, 60));
        jLabel13.setText("Costo de compra anual:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(60, 60, 60));
        jLabel14.setText("Costo total:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(60, 60, 60));
        jLabel16.setText("Costo de orden anual:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtCMA.setBackground(new java.awt.Color(209, 231, 191));
        txtCMA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCMA.setForeground(new java.awt.Color(51, 51, 51));
        txtCMA.setBorder(null);
        txtCMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMAActionPerformed(evt);
            }
        });
        jPanel4.add(txtCMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 110, 21));

        txtPA.setBackground(new java.awt.Color(209, 231, 191));
        txtPA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPA.setForeground(new java.awt.Color(51, 51, 51));
        txtPA.setBorder(null);
        txtPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAActionPerformed(evt);
            }
        });
        jPanel4.add(txtPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 21));

        txtCOA.setBackground(new java.awt.Color(209, 231, 191));
        txtCOA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCOA.setForeground(new java.awt.Color(51, 51, 51));
        txtCOA.setBorder(null);
        txtCOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOAActionPerformed(evt);
            }
        });
        jPanel4.add(txtCOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 21));

        jSeparator13.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, 10));

        jSeparator14.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 110, 10));

        jSeparator15.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 110, 10));

        txtQ.setBackground(new java.awt.Color(209, 231, 191));
        txtQ.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtQ.setForeground(new java.awt.Color(51, 51, 51));
        txtQ.setBorder(null);
        txtQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQActionPerformed(evt);
            }
        });
        jPanel4.add(txtQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 120, 21));

        txtIP.setBackground(new java.awt.Color(209, 231, 191));
        txtIP.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtIP.setForeground(new java.awt.Color(51, 51, 51));
        txtIP.setBorder(null);
        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });
        jPanel4.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 110, 21));

        txtCCA.setBackground(new java.awt.Color(209, 231, 191));
        txtCCA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCCA.setForeground(new java.awt.Color(51, 51, 51));
        txtCCA.setBorder(null);
        txtCCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCAActionPerformed(evt);
            }
        });
        jPanel4.add(txtCCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 110, 21));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 780, 490));

        jPanel5.setBackground(new java.awt.Color(209, 231, 191));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Datos a ingresar:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 26, -1, 31));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(60, 60, 60));
        jLabel7.setText("Demanda anual:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 112, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(60, 60, 60));
        jLabel8.setText("Costo por ordenar:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(60, 60, 60));
        jLabel11.setText("Costo por mantener:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(60, 60, 60));
        jLabel12.setText("Costo unitario:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 182, -1, -1));

        txtDA.setBackground(new java.awt.Color(209, 231, 191));
        txtDA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDA.setForeground(new java.awt.Color(153, 153, 153));
        txtDA.setText("D");
        txtDA.setBorder(null);
        txtDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDAMousePressed(evt);
            }
        });
        txtDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDAActionPerformed(evt);
            }
        });
        txtDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDAKeyTyped(evt);
            }
        });
        jPanel5.add(txtDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 110, 120, 21));

        txtCU.setBackground(new java.awt.Color(209, 231, 191));
        txtCU.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCU.setForeground(new java.awt.Color(153, 153, 153));
        txtCU.setText("C");
        txtCU.setBorder(null);
        txtCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCUMousePressed(evt);
            }
        });
        txtCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUActionPerformed(evt);
            }
        });
        txtCU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCUKeyTyped(evt);
            }
        });
        jPanel5.add(txtCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 130, 21));

        txtCM.setBackground(new java.awt.Color(209, 231, 191));
        txtCM.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCM.setForeground(new java.awt.Color(153, 153, 153));
        txtCM.setText("H");
        txtCM.setBorder(null);
        txtCM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCMMousePressed(evt);
            }
        });
        txtCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMActionPerformed(evt);
            }
        });
        txtCM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCMKeyTyped(evt);
            }
        });
        jPanel5.add(txtCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 250, 130, 21));

        txtCO.setBackground(new java.awt.Color(209, 231, 191));
        txtCO.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCO.setForeground(new java.awt.Color(153, 153, 153));
        txtCO.setText("S");
        txtCO.setBorder(null);
        txtCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCOMousePressed(evt);
            }
        });
        txtCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOActionPerformed(evt);
            }
        });
        txtCO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCOKeyTyped(evt);
            }
        });
        jPanel5.add(txtCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 320, 130, 21));

        btnCal.setBackground(new java.awt.Color(204, 204, 255));
        btnCal.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCal.setForeground(new java.awt.Color(102, 102, 102));
        btnCal.setText("Calcular");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        jPanel5.add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 407, 118, 36));

        btnLim.setBackground(new java.awt.Color(204, 204, 255));
        btnLim.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnLim.setForeground(new java.awt.Color(102, 102, 102));
        btnLim.setText("Limpiar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });
        jPanel5.add(btnLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 407, 118, 36));

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 130, 10));

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 10));

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 10));

        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 10));

        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 10));

        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 10));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 380, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        INDEX regresar = new INDEX();
        regresar.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTActionPerformed

    private void txtDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDAActionPerformed

    private void txtCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCUActionPerformed

    private void txtCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMActionPerformed

    private void txtCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOActionPerformed

    private void txtCMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMAActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void txtCOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOAActionPerformed

    private void txtQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtCCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCAActionPerformed

    private void txtDAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDAMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().equals("D")) {
            txtDA.setText("");
            txtDA.setForeground(java.awt.Color.black);
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDAMousePressed

    private void txtCUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCUMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCU.getText().equals("C")) {
            txtCU.setText("");
            txtCU.setForeground(java.awt.Color.black);
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCUMousePressed

    private void txtCMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCM.getText().equals("H")) {
            txtCM.setText("");
            txtCM.setForeground(java.awt.Color.black);
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCMMousePressed

    private void txtCOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCOMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new java.awt.Color(153, 153, 153));
        }
        if (txtCO.getText().equals("S")) {
            txtCO.setText("");
            txtCO.setForeground(java.awt.Color.black);
        }
    }//GEN-LAST:event_txtCOMousePressed

    private void txtDAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDAKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }    
    }//GEN-LAST:event_txtDAKeyTyped

    private void txtCUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCUKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }    
    }//GEN-LAST:event_txtCUKeyTyped

    private void txtCMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }    
    }//GEN-LAST:event_txtCMKeyTyped

    private void txtCOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }    
    }//GEN-LAST:event_txtCOKeyTyped

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
         //Declarar variables
        double demAn, costpOrd, costpMan, costUn, cantOp, invProm, numPedAn, costCompAn, costPedAn, costManAn, costTot;
        
        demAn = Double.parseDouble(txtDA.getText());
        costUn = Double.parseDouble(txtCU.getText());
        costpMan = Double.parseDouble(txtCM.getText());
        costpOrd = Double.parseDouble(txtCO.getText());
        
        
        //Operaciones
        cantOp = Math.sqrt((2*demAn*costpOrd)/costpMan);
        invProm = cantOp / 2;
        numPedAn = demAn / cantOp;
        costCompAn = demAn * costUn;
        costPedAn = (demAn/cantOp) * costpOrd;
        costManAn = (cantOp / 2) * costpMan;
        costTot = costCompAn + costPedAn + costManAn;
        
        //Mostrar resultados
        txtQ.setText(String.format("%.2f", cantOp));
        txtIP.setText(String.format("%.2f", invProm));
        txtPA.setText(String.format("%.2f", numPedAn));
        txtCCA.setText(String.format("%.2f",costCompAn));
        txtCOA.setText(String.format("%.2f", costPedAn));
        txtCMA.setText(String.format("%.2f", costManAn));
        txtCT.setText(String.format("%.2f", costTot));
    }//GEN-LAST:event_btnCalActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimActionPerformed
    
    private void Limpiar(){
        for(Component component: jPanel5.getComponents()){
            if (component instanceof JTextField ){
                ((JTextField) component).setText("");
            }
        }
          for(Component component: jPanel4.getComponents()){
            if (component instanceof JTextField ){
                ((JTextField) component).setText("");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EOQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EOQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EOQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EOQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EOQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtCCA;
    private javax.swing.JTextField txtCM;
    private javax.swing.JTextField txtCMA;
    private javax.swing.JTextField txtCO;
    private javax.swing.JTextField txtCOA;
    private javax.swing.JTextField txtCT;
    private javax.swing.JTextField txtCU;
    private javax.swing.JTextField txtDA;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtQ;
    // End of variables declaration//GEN-END:variables
}
