/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_io_u4;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Britany Morales
 */
public class EOQ_Re2 extends javax.swing.JFrame {

    /**
     * Creates new form EOQ_Re2
     */
    public EOQ_Re2() {
        initComponents();
        this.setExtendedState(EOQ_Re2.MAXIMIZED_BOTH);
        txtQ.setEditable(false);
        txtIP.setEditable(false);
        txtPA.setEditable(false);
        txtCCA.setEditable(false);
        txtCOA.setEditable(false);
        txtCMA.setEditable(false);
        txtCT.setEditable(false);
        txtPR.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCMA = new javax.swing.JTextField();
        txtPA = new javax.swing.JTextField();
        txtCOA = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        txtQ = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        txtCCA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        txtPR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        txtCT = new javax.swing.JTextField();
        txtCT2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDA = new javax.swing.JTextField();
        txtCU = new javax.swing.JTextField();
        txtCM = new javax.swing.JTextField();
        txtDAN = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        txtCO = new javax.swing.JTextField();
        txtTE = new javax.swing.JTextField();
        txtDd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 228, 178));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(126, 170, 146));

        jButton1.setBackground(new java.awt.Color(158, 210, 190));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Regresar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" CANTIDAD ECONÓMICA A ORDENAR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 90));

        jPanel4.setBackground(new java.awt.Color(209, 231, 191));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Resultados:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 60, 60));
        jLabel3.setText("Cantidad óptima:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("Costo de mantenimiento anual:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 60, 60));
        jLabel5.setText("Pedidos anuales:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 60, 60));
        jLabel6.setText("Inventario promedio:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 110, 10));

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, 10));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, 10));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 120, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(60, 60, 60));
        jLabel13.setText("Costo de compra anual:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(60, 60, 60));
        jLabel16.setText("Costo de orden anual:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtCMA.setBackground(new java.awt.Color(209, 231, 191));
        txtCMA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCMA.setForeground(new java.awt.Color(51, 51, 51));
        txtCMA.setBorder(null);
        txtCMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMAActionPerformed(evt);
            }
        });
        txtCMA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCMAKeyTyped(evt);
            }
        });
        jPanel4.add(txtCMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 110, 21));

        txtPA.setBackground(new java.awt.Color(209, 231, 191));
        txtPA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPA.setForeground(new java.awt.Color(51, 51, 51));
        txtPA.setBorder(null);
        txtPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAActionPerformed(evt);
            }
        });
        txtPA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPAKeyTyped(evt);
            }
        });
        jPanel4.add(txtPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 21));

        txtCOA.setBackground(new java.awt.Color(209, 231, 191));
        txtCOA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCOA.setForeground(new java.awt.Color(51, 51, 51));
        txtCOA.setBorder(null);
        txtCOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOAActionPerformed(evt);
            }
        });
        txtCOA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCOAKeyTyped(evt);
            }
        });
        jPanel4.add(txtCOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 21));

        jSeparator13.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, 10));

        jSeparator14.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 110, 10));

        jSeparator15.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 110, 10));

        txtQ.setBackground(new java.awt.Color(209, 231, 191));
        txtQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQ.setForeground(new java.awt.Color(51, 51, 51));
        txtQ.setBorder(null);
        txtQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQActionPerformed(evt);
            }
        });
        txtQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQKeyTyped(evt);
            }
        });
        jPanel4.add(txtQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 120, 21));

        txtIP.setBackground(new java.awt.Color(209, 231, 191));
        txtIP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIP.setForeground(new java.awt.Color(51, 51, 51));
        txtIP.setBorder(null);
        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });
        txtIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIPKeyTyped(evt);
            }
        });
        jPanel4.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 110, 21));

        txtCCA.setBackground(new java.awt.Color(209, 231, 191));
        txtCCA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCCA.setForeground(new java.awt.Color(51, 51, 51));
        txtCCA.setBorder(null);
        txtCCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCAActionPerformed(evt);
            }
        });
        txtCCA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCCAKeyTyped(evt);
            }
        });
        jPanel4.add(txtCCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 110, 21));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(60, 60, 60));
        jLabel20.setText("Punto de reorden:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jSeparator18.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 120, 10));

        txtPR.setBackground(new java.awt.Color(209, 231, 191));
        txtPR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPR.setForeground(new java.awt.Color(51, 51, 51));
        txtPR.setBorder(null);
        txtPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRActionPerformed(evt);
            }
        });
        txtPR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPRKeyTyped(evt);
            }
        });
        jPanel4.add(txtPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 120, 21));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(60, 60, 60));
        jLabel21.setText("Costo total:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jSeparator19.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, 10));

        txtCT.setBackground(new java.awt.Color(209, 231, 191));
        txtCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCT.setForeground(new java.awt.Color(51, 51, 51));
        txtCT.setBorder(null);
        txtCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTActionPerformed(evt);
            }
        });
        txtCT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCTKeyTyped(evt);
            }
        });
        jPanel4.add(txtCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, 21));

        txtCT2.setBackground(new java.awt.Color(209, 231, 191));
        txtCT2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCT2.setForeground(new java.awt.Color(51, 51, 51));
        txtCT2.setText("0");
        txtCT2.setBorder(null);
        txtCT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCT2ActionPerformed(evt);
            }
        });
        txtCT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCT2KeyTyped(evt);
            }
        });
        jPanel4.add(txtCT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, 21));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 780, 500));

        jPanel5.setBackground(new java.awt.Color(209, 231, 191));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Datos a ingresar:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 31));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(60, 60, 60));
        jLabel7.setText("Demanda anual:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(60, 60, 60));
        jLabel11.setText("Costo por mantener:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(60, 60, 60));
        jLabel12.setText("Costo unitario:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtDA.setBackground(new java.awt.Color(209, 231, 191));
        txtDA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDA.setForeground(new java.awt.Color(153, 153, 153));
        txtDA.setText("D");
        txtDA.setBorder(null);
        txtDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDAMousePressed(evt);
            }
        });
        txtDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDAActionPerformed(evt);
            }
        });
        txtDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDAKeyTyped(evt);
            }
        });
        jPanel5.add(txtDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, 21));

        txtCU.setBackground(new java.awt.Color(209, 231, 191));
        txtCU.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCU.setForeground(new java.awt.Color(153, 153, 153));
        txtCU.setText("C");
        txtCU.setBorder(null);
        txtCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCUMousePressed(evt);
            }
        });
        txtCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUActionPerformed(evt);
            }
        });
        txtCU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCUKeyTyped(evt);
            }
        });
        jPanel5.add(txtCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 21));

        txtCM.setBackground(new java.awt.Color(209, 231, 191));
        txtCM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCM.setForeground(new java.awt.Color(153, 153, 153));
        txtCM.setText("H");
        txtCM.setBorder(null);
        txtCM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCMMousePressed(evt);
            }
        });
        txtCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMActionPerformed(evt);
            }
        });
        txtCM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCMKeyTyped(evt);
            }
        });
        jPanel5.add(txtCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, 21));

        txtDAN.setBackground(new java.awt.Color(209, 231, 191));
        txtDAN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDAN.setForeground(new java.awt.Color(153, 153, 153));
        txtDAN.setText("0");
        txtDAN.setBorder(null);
        txtDAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDANMousePressed(evt);
            }
        });
        txtDAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDANActionPerformed(evt);
            }
        });
        txtDAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDANKeyTyped(evt);
            }
        });
        jPanel5.add(txtDAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 130, 21));

        btnCalc.setBackground(new java.awt.Color(204, 204, 255));
        btnCalc.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCalc.setForeground(new java.awt.Color(102, 102, 102));
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        jPanel5.add(btnCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 118, 36));

        btnLim.setBackground(new java.awt.Color(204, 204, 255));
        btnLim.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnLim.setForeground(new java.awt.Color(102, 102, 102));
        btnLim.setText("Limpiar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });
        jPanel5.add(btnLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 118, 36));

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, 10));

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 10));

        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 130, 10));

        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 10));

        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(60, 60, 60));
        jLabel15.setText("Costo por ordenar:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(60, 60, 60));
        jLabel17.setText("Días por año:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(60, 60, 60));
        jLabel18.setText("Demanda diaria:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(60, 60, 60));
        jLabel19.setText("Tiempo de entrega:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jSeparator16.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 130, 10));

        jSeparator17.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 130, 10));

        txtCO.setBackground(new java.awt.Color(209, 231, 191));
        txtCO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCO.setForeground(new java.awt.Color(153, 153, 153));
        txtCO.setText("S");
        txtCO.setBorder(null);
        txtCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCOMousePressed(evt);
            }
        });
        txtCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOActionPerformed(evt);
            }
        });
        txtCO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCOKeyTyped(evt);
            }
        });
        jPanel5.add(txtCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 130, 21));

        txtTE.setBackground(new java.awt.Color(209, 231, 191));
        txtTE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTE.setForeground(new java.awt.Color(153, 153, 153));
        txtTE.setText("Días");
        txtTE.setBorder(null);
        txtTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTEMousePressed(evt);
            }
        });
        txtTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTEActionPerformed(evt);
            }
        });
        txtTE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTEKeyTyped(evt);
            }
        });
        jPanel5.add(txtTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 130, 21));

        txtDd.setBackground(new java.awt.Color(209, 231, 191));
        txtDd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDd.setForeground(new java.awt.Color(153, 153, 153));
        txtDd.setText("d");
        txtDd.setBorder(null);
        txtDd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDdMousePressed(evt);
            }
        });
        txtDd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDdActionPerformed(evt);
            }
        });
        txtDd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDdKeyTyped(evt);
            }
        });
        jPanel5.add(txtDd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 21));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 380, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        INDEX regresar = new INDEX();
        regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMAActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void txtCOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOAActionPerformed

    private void txtQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQActionPerformed

    private void txtQKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQKeyTyped
        // TODO add your handling code here:      
    }//GEN-LAST:event_txtQKeyTyped

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtCCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCAActionPerformed

    private void txtPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRActionPerformed

    private void txtDAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDAMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().equals("D")) {
            txtDA.setText("");
            txtDA.setForeground(Color.black);
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtDd.getText().isEmpty()) {
            txtDd.setText("d");
            txtDd.setForeground(new Color(153, 153, 153));
        }
        if (txtTE.getText().isEmpty()) {
            txtTE.setText("Días");
            txtTE.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDAMousePressed

    private void txtDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDAActionPerformed

    private void txtDAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDAKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtDAKeyTyped

    private void txtCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCUActionPerformed

    private void txtCUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCUKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtCUKeyTyped

    private void txtCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMActionPerformed

    private void txtCMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtCMKeyTyped

    private void txtDANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDANActionPerformed

    private void txtDANKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDANKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtDANKeyTyped

    private void txtCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOActionPerformed

    private void txtCOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtCOKeyTyped

    private void txtTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTEActionPerformed

    private void txtTEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTEKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtTEKeyTyped

    private void txtDdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDdActionPerformed

    private void txtDdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDdKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo ingresar números");
        }
    }//GEN-LAST:event_txtDdKeyTyped

    private void txtCUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCUMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().equals("C")) {
            txtCU.setText("");
            txtCU.setForeground(Color.black);
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtDd.getText().isEmpty()) {
            txtDd.setText("d");
            txtDd.setForeground(new Color(153, 153, 153));
        }
        if (txtTE.getText().isEmpty()) {
            txtTE.setText("Días");
            txtTE.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCUMousePressed

    private void txtCMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().equals("H")) {
            txtCM.setText("");
            txtCM.setForeground(Color.black);
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtDd.getText().isEmpty()) {
            txtDd.setText("d");
            txtDd.setForeground(new Color(153, 153, 153));
        }
        if (txtTE.getText().isEmpty()) {
            txtTE.setText("Días");
            txtTE.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCMMousePressed

    private void txtCOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCOMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().equals("S")) {
            txtCO.setText("");
            txtCO.setForeground(Color.black);
        }
        if (txtDd.getText().isEmpty()) {
            txtDd.setText("d");
            txtDd.setForeground(new Color(153, 153, 153));
        }
        if (txtTE.getText().isEmpty()) {
            txtTE.setText("Días");
            txtTE.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCOMousePressed

    private void txtDdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDdMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtDd.getText().equals("d")) {
            txtDd.setText("");
            txtDd.setForeground(Color.black);
        }
        if (txtTE.getText().isEmpty()) {
            txtTE.setText("Días");
            txtTE.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDdMousePressed

    private void txtTEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTEMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtDd.getText().isEmpty()) {
            txtDd.setText("d");
            txtDd.setForeground(new Color(153, 153, 153));
        }
        if (txtTE.getText().equals("Días")) {
            txtTE.setText("");
            txtTE.setForeground(Color.black);
        }
        if (txtDAN.getText().isEmpty()) {
            txtDAN.setText("0");
            txtDAN.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtTEMousePressed

    private void txtDANMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDANMousePressed
        // TODO add your handling code here:
        if (txtDA.getText().isEmpty()) {
            txtDA.setText("D");
            txtDA.setForeground(new Color(153, 153, 153));
        }
        if (txtCU.getText().isEmpty()) {
            txtCU.setText("C");
            txtCU.setForeground(new Color(153, 153, 153));
        }
        if (txtCM.getText().isEmpty()) {
            txtCM.setText("H");
            txtCM.setForeground(new Color(153, 153, 153));
        }
        if (txtCO.getText().isEmpty()) {
            txtCO.setText("S");
            txtCO.setForeground(new Color(153, 153, 153));
        }
        if (txtDd.getText().isEmpty()) {
            txtDd.setText("d");
            txtDd.setForeground(new Color(153, 153, 153));
        }
        if (txtTE.getText().isEmpty()) {
            txtTE.setText("Días");
            txtTE.setForeground(new Color(153, 153, 153));
        }
        if (txtDAN.getText().equals("0")) {
            txtDAN.setText("");
            txtDAN.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtDANMousePressed

    private void txtPAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPAKeyTyped
        // TODO add your handling code here:  
    }//GEN-LAST:event_txtPAKeyTyped

    private void txtIPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPKeyTyped

    private void txtCCAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCCAKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCAKeyTyped

    private void txtCOAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOAKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOAKeyTyped

    private void txtCMAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMAKeyTyped
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtCMAKeyTyped

    private void txtPRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPRKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRKeyTyped

    private void txtCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTActionPerformed

    private void txtCTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCTKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTKeyTyped

    private void txtCT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCT2ActionPerformed

    private void txtCT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCT2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCT2KeyTyped

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        //Declarar variables
        double demAn, costpOrd, costpMan, costUn, deDiaria, tiemEntre, diasxA, cantOp, invProm, numPedAn, costCompAn, costPedAn, costManAn, costTot, ptoRe;

        demAn = Double.parseDouble(txtDA.getText());
        costUn = Double.parseDouble(txtCU.getText());
        costpMan = Double.parseDouble(txtCM.getText());
        costpOrd = Double.parseDouble(txtCO.getText());
        deDiaria = Double.parseDouble(txtDd.getText());
        tiemEntre = Double.parseDouble(txtTE.getText());
        diasxA = Double.parseDouble(txtDAN.getText());

        //Operaciones
        cantOp = Math.sqrt((2 * demAn * costpOrd) / costpMan);
        invProm = cantOp / 2;
        numPedAn = demAn / cantOp;
        costCompAn = demAn * costUn;
        costPedAn = (demAn / cantOp) * costpOrd;
        costManAn = (cantOp / 2) * costpMan;
        costTot = costCompAn + costPedAn + costManAn;

        if (tiemEntre == 0) {
            if (numPedAn != 0) {
                tiemEntre = diasxA / numPedAn;
            }
        }

        if (deDiaria == 0) {
            if (diasxA != 0) {
                deDiaria = demAn / diasxA;
            }
        }
        ptoRe = deDiaria * tiemEntre;

        //Mostrar resultados
        txtQ.setText(String.format("%.2f", cantOp));
        txtIP.setText(String.format("%.2f", invProm));
        txtPA.setText(String.format("%.2f", numPedAn));
        txtCCA.setText(String.format("%.2f", costCompAn));
        txtCOA.setText(String.format("%.2f", costPedAn));
        txtCMA.setText(String.format("%.2f", costManAn));
        txtCT.setText(String.format("%.2f", costTot));
        txtPR.setText(String.format("%.2f", ptoRe));
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimActionPerformed
    private void Limpiar() {
        for (Component component : jPanel5.getComponents()) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }
        }
        for (Component component : jPanel4.getComponents()) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EOQ_Re2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EOQ_Re2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EOQ_Re2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EOQ_Re2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EOQ_Re2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtCCA;
    private javax.swing.JTextField txtCM;
    private javax.swing.JTextField txtCMA;
    private javax.swing.JTextField txtCO;
    private javax.swing.JTextField txtCOA;
    private javax.swing.JTextField txtCT;
    private javax.swing.JTextField txtCT2;
    private javax.swing.JTextField txtCU;
    private javax.swing.JTextField txtDA;
    private javax.swing.JTextField txtDAN;
    private javax.swing.JTextField txtDd;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPR;
    private javax.swing.JTextField txtQ;
    private javax.swing.JTextField txtTE;
    // End of variables declaration//GEN-END:variables
}
