/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_io_u4;

import java.awt.Color;

/**
 *
 * @author vanes
 */
public class INDEX extends javax.swing.JFrame {

    FormatoTiempo tm=new FormatoTiempo();
    
    public INDEX() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        mostrarTiempo();
       
    }
    
    public void mostrarTiempo(){
           lb_hora.setText(tm.horaFormateada);
            lb_fecha.setText(tm.fechaFormateada);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_EOQ = new javax.swing.JButton();
        btn_cantidadEC = new javax.swing.JButton();
        btn_descuento = new javax.swing.JButton();
        BTN_ABC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_hora = new javax.swing.JLabel();
        btn_doc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INDEX");

        jPanel1.setBackground(new java.awt.Color(200, 228, 178));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("UNIDAD 4. TEORÍA DE INVENTARIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel2.setText("MENÚ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        btn_EOQ.setBackground(new java.awt.Color(158, 210, 190));
        btn_EOQ.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btn_EOQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/produccion3.png"))); // NOI18N
        btn_EOQ.setText("CANTIDAD ECONOMICA A PRODUCIR (EOQ)");
        btn_EOQ.setBorder(null);
        btn_EOQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EOQ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_EOQ.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_EOQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EOQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EOQMouseExited(evt);
            }
        });
        btn_EOQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EOQActionPerformed(evt);
            }
        });
        jPanel1.add(btn_EOQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 370, 170));

        btn_cantidadEC.setBackground(new java.awt.Color(158, 210, 190));
        btn_cantidadEC.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btn_cantidadEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/producto1.png"))); // NOI18N
        btn_cantidadEC.setText("CANTIDAD ECONOMICA (EOQ)");
        btn_cantidadEC.setBorder(null);
        btn_cantidadEC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cantidadEC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cantidadEC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cantidadEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cantidadECMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cantidadECMouseExited(evt);
            }
        });
        btn_cantidadEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cantidadECActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cantidadEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 250, 120));

        btn_descuento.setBackground(new java.awt.Color(158, 210, 190));
        btn_descuento.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btn_descuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/descuento2.png"))); // NOI18N
        btn_descuento.setText("DESCUENTOS POR CANTIDAD");
        btn_descuento.setBorder(null);
        btn_descuento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_descuento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_descuento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_descuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_descuentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_descuentoMouseExited(evt);
            }
        });
        btn_descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descuentoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 250, 120));

        BTN_ABC.setBackground(new java.awt.Color(158, 210, 190));
        BTN_ABC.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BTN_ABC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/a-b-c-4.png"))); // NOI18N
        BTN_ABC.setText("ANALISIS ABC");
        BTN_ABC.setBorder(null);
        BTN_ABC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_ABC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_ABC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_ABC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN_ABCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN_ABCMouseExited(evt);
            }
        });
        BTN_ABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ABCActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_ABC, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 250, 120));

        jPanel2.setBackground(new java.awt.Color(126, 170, 146));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 100, 40));

        lb_fecha.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lb_fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_fecha.setText("DD/MM/YYYY");
        lb_fecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 150, 40));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hora");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, 40));

        lb_hora.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lb_hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hora.setText("hh:mm:ss");
        lb_hora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lb_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 130, 40));

        btn_doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Manual.png"))); // NOI18N
        btn_doc.setText("Documento");
        btn_doc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_docMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_docMouseExited(evt);
            }
        });
        jPanel2.add(btn_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 170, 80));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconInvt.png"))); // NOI18N
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 170, 150));

        jSeparator1.setForeground(new java.awt.Color(20, 195, 142));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 250, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 320, 700));

        jRadioButton1.setBackground(new java.awt.Color(200, 228, 178));
        jRadioButton1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jRadioButton1.setText("Punto de reorden");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EOQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EOQActionPerformed
        // TODO add your handling code here:
        EOQ abrir=new EOQ();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_EOQActionPerformed

    private void btn_cantidadECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cantidadECActionPerformed
        // TODO add your handling code here:
        Cantidad_economica abrir = new Cantidad_economica();
        abrir.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_cantidadECActionPerformed

    private void btn_descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descuentoActionPerformed
        // TODO add your handling code here:
        desc_p_cant abrir =  new desc_p_cant();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_descuentoActionPerformed

    private void BTN_ABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ABCActionPerformed
        // TODO add your handling code here:
        an_abc abrir = new an_abc();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_BTN_ABCActionPerformed

    private void btn_descuentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_descuentoMouseEntered
        // TODO add your handling code here:
        btn_descuento.setBackground(new Color(158, 178, 210));
    }//GEN-LAST:event_btn_descuentoMouseEntered

    private void btn_descuentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_descuentoMouseExited
        // TODO add your handling code here:
        btn_descuento.setBackground(new Color(158,210,190));
    }//GEN-LAST:event_btn_descuentoMouseExited

    private void btn_cantidadECMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cantidadECMouseExited
        // TODO add your handling code here:
         btn_cantidadEC.setBackground(new Color(158,210,190));
    }//GEN-LAST:event_btn_cantidadECMouseExited

    private void btn_cantidadECMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cantidadECMouseEntered
        // TODO add your handling code here:
        btn_cantidadEC.setBackground(new Color(158, 178, 210));
    }//GEN-LAST:event_btn_cantidadECMouseEntered

    private void btn_EOQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EOQMouseEntered
        // TODO add your handling code here:
        btn_EOQ.setBackground(new Color(158, 178, 210));
    }//GEN-LAST:event_btn_EOQMouseEntered

    private void btn_EOQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EOQMouseExited
        // TODO add your handling code here:
        btn_EOQ.setBackground(new Color(158,210,190));
    }//GEN-LAST:event_btn_EOQMouseExited

    private void BTN_ABCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_ABCMouseEntered
        // TODO add your handling code here:
         BTN_ABC.setBackground(new Color(158, 178, 210));
    }//GEN-LAST:event_BTN_ABCMouseEntered

    private void BTN_ABCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_ABCMouseExited
        // TODO add your handling code here:
         BTN_ABC.setBackground(new Color(158,210,190));
    }//GEN-LAST:event_BTN_ABCMouseExited

    private void btn_docMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_docMouseEntered
        // TODO add your handling code here:
        btn_doc.setBackground(new Color(158, 178, 210));
    }//GEN-LAST:event_btn_docMouseEntered

    private void btn_docMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_docMouseExited
        // TODO add your handling code here:
        btn_doc.setBackground(new Color(158,210,190));
    }//GEN-LAST:event_btn_docMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INDEX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ABC;
    private javax.swing.JButton btn_EOQ;
    private javax.swing.JButton btn_cantidadEC;
    private javax.swing.JButton btn_descuento;
    private javax.swing.JButton btn_doc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_hora;
    // End of variables declaration//GEN-END:variables
}
